### ISSUE TITLE
 SyntaxError: Cannot use import statement outside a module '@polkadot/util-crypto'

### ISSUE THREAD

**Issue by GrandinLuc** [polkadot-js/docs#152]
So I came up with this issue when trying to use '@polkadot/util-crypto', I provided a .zip file with a simplified code version displaying the same error I have. I tried the solutions showed in the error message without success and then I started messing around with jest.config without success either. I would very much appreciate help on that matter and I thank in advance anyone who would help me with this.

Here is roughly the error message I get:

```
   Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/luc/Documents/infrastructure/lib/services/blockchain-wallets/polkadot-wallet/node_modules/@polkadot/util-crypto/index.js:3
    import "./cryptoInit.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
    > 1 | import {signatureVerify} from '@polkadot/util-crypto'
       2 | ^

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/polkadot-signer.ts:11:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.646 s
Ran all test suites matching /spec/i.
```

[polkadot-wallet.zip](https://github.com/polkadot-js/docs/files/6392439/polkadot-wallet.zip)

**Comment by jacogr** [comment]
This is what the API (common/util repo has the same) uses for Jest - https://github.com/polkadot-js/api/blob/master/jest.config.cjs#L30

**Comment by GrandinLuc** [comment]
Thanks for the swift response ! What you sent me fixes my problem but create a new one: it seems like my TypeScript isn't transpiled correctly as the type declarations are seen as Syntax Error when running my tests

**Comment by jacogr** [comment]
This issue has been open for 21 days with no activity and is not labelled as an enhancement. It will be closed in 7 days.
