### ISSUE TITLE
Example in examples/create-mnemonic.md crashes with an error

### ISSUE THREAD

**Issue by sgerodes** [polkadot-js/docs#379]
I as using the example in the following document: 
https://github.com/polkadot-js/docs/blob/master/docs/util-crypto/examples/create-mnemonic.md

I was using the same code, nothing was altered.
When executed locally it crashes with the following error:

Generated mnemonic: lend sad wall salute ride scare muscle usage trick nasty high busy
isValidMnemonic: true
Error: bad secret key size
    at Function.nacl.sign.keyPair.fromSecretKey (/Users/sergeyg/WebstormProjects/mnemonic_test/node_modules/tweetnacl/nacl-fast.js:2320:11)
    at ed25519PairFromSecret (/Users/sergeyg/WebstormProjects/mnemonic_test/node_modules/@polkadot/util-crypto/cjs/ed25519/pair/fromSecret.js:27:42)
    at main (/Users/sergeyg/WebstormProjects/mnemonic_test/src/mnemonic_test.js:23:38)
    at Object.<anonymous> (/Users/sergeyg/WebstormProjects/mnemonic_test/src/mnemonic_test.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by sgerodes** [comment]
Fast inspection of the code I think "fromSecretKey(secret)" in "ed25519PairFromSecret" should be replaced with "fromSeed(secret)"
