### ISSUE TITLE
Ganar-lo-perdido-sin-saltos-cuanticos

### ISSUE THREAD

**Issue by asggWa** [polkadot-js/docs#460]
I install the system trying to do it following a line. I try to correct dependencies without leaving anything behind.
As a notable tester, I close my eyes and execute.

Uncaught Exception:
Error: spawn /home/alfonso/snap/parity-ui/38/.config/parity-ui/parity ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jacogr** [comment]
This is not parity-ui.
